const { chromium } = require('playwright');

const urls = [
  'https://sanand0.github.io/tdsdata/js_table/?seed=77',
  'https://sanand0.github.io/tdsdata/js_table/?seed=78',
  'https://sanand0.github.io/tdsdata/js_table/?seed=79',
  'https://sanand0.github.io/tdsdata/js_table/?seed=80',
  'https://sanand0.github.io/tdsdata/js_table/?seed=81',
  'https://sanand0.github.io/tdsdata/js_table/?seed=82',
  'https://sanand0.github.io/tdsdata/js_table/?seed=83',
  'https://sanand0.github.io/tdsdata/js_table/?seed=84',
  'https://sanand0.github.io/tdsdata/js_table/?seed=85',
  'https://sanand0.github.io/tdsdata/js_table/?seed=86',
];

(async () => {
  // Launch a headless (invisible) browser
  const browser = await chromium.launch();
  const page = await browser.newPage();

  let grandTotal = 0;

  for (const url of urls) {
    await page.goto(url);

    // Wait for the table to load (it's dynamically generated by JavaScript)
    await page.waitForSelector('table');

    // Get all numbers from all table cells
    const pageSum = await page.evaluate(() => {
      const cells = document.querySelectorAll('table td');
      let sum = 0;
      cells.forEach(cell => {
        const num = parseFloat(cell.innerText);
        if (!isNaN(num)) sum += num;
      });
      return sum;
    });

    console.log(`Sum for ${url}: ${pageSum}`);
    grandTotal += pageSum;
  }

  console.log(`Total sum across all pages: ${grandTotal}`);
  await browser.close();
})();
